### ISSUE TITLE
restore is never called in afterEach

### ISSUE THREAD

**Issue by phryneas** [kevin940726/console-testing-library#1]
https://github.com/kevin940726/console-testing-library/blob/master/index.js#L216-L224

In this codesnippet, you are calling `afterEach(restore);` - this way, the reference to the temporary value `() => {}` is passed to afterEach, even if you change the instance of `restore`, that will not be passed to `afterEach`.

Do something like `afterEach(() => restore())` instead :)

**Comment by kevin940726** [comment]
Oops! That is indeed my fault! Thanks for spotting that!

Unfortunately looks like this doesn't fix the node 13.2 issue 😅
