### ISSUE TITLE
[Feature] Expose stdout and stderr

### ISSUE THREAD

**Issue by nulltoken** [kevin940726/console-testing-library#13]
:wave: @kevin940726 

Would you be open to tweak `TestingConsoleInstance` so that it exposes `stderr` and `stdout` string properties?

`stdout` would be valued by invocations leveraging `log` and `info`, and `stderr` by `warn` and `error`.

**Comment by kevin940726** [comment]
I wonder if `stderr` and `stdout` are valid concepts in browser environment? I recall that it's the reason I don't want to expose those in the first place. But again, I don't think exposing them to Node environment only would be a bad idea. PR welcome!

**Comment by nulltoken** [comment]
>I wonder if stderr and stdout are valid concepts in browser environment?

I indeed didn't think of the browser environment with regards to that proposal. Would that be blocking?

**Comment by kevin940726** [comment]
No I don't think it would be blocking. Just that it won't be relevant in browser environment, and we need proper documentation :).
